### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jwoertink** [naqvis/crystar#15]
Do you have plans to push a release soon, or would you consider doing a patch release? Lucky actually depends on this shards through Flow https://github.com/luckyframework/lucky_flow/issues/153 and though, we could just point to master branch, if you're planning a release soon, we can wait on that.

Thanks!

**Comment by naqvis** [comment]
Oops! sorry missed this issue. Going to release new version

**Comment by jwoertink** [comment]
Thank you! :raised_hands:
