### ISSUE TITLE
你好，naqvis.                                                                          

### ISSUE THREAD

**Issue by zw963** [naqvis/crystar#16]
你好，naqvis 前辈，考虑到你很早就开始使用 Crystal, 为 Crystal 做出了那么多贡献，叫你一声前辈, 完全不过分，而我是一个加入刚满一年的新人。

你我都是为数不多的至今还在使用 Crystal 的开发者 （多人都放弃离开了），你有考虑我们一起来维护 Crystal-China github 组织吗？ 我可以加你为拥有者。

我也注册了 crystal-china.org 域名，但是还没有时间创建站点。本来想 twitter 问你，不过考虑这里看到的人少一些，所以在这里 @ 你一下。

**Comment by naqvis** [comment]
@zw963 你好Billy，不好意思才看到这个issue。创建组织或者域名不是个问题，问题是维护和运营。我看到自从你加入Crystal community一直都是很活跃，也相信你也是Crystal的热爱者。有机会我们可以相互学习和交流。

**Comment by zw963** [comment]
Hi, naqvis.

> 创建组织或者域名不是个问题，问题是维护和运营。

是啊，这的确是个问题，最近有点事，又 delay 了，哈哈，而且，这方面还没有经验。

> 有机会我们可以相互学习和交流。

我相信有很多问题可以一起交流的，也可以一起做点什么有意思的项目。

方便交流一下联系方式吗？ 我希望咱们有私信的方式，用母语交流总是容易一些， 方便的话，你可以 t.me/crystal_cn 入群，然后私信我。

**Comment by zw963** [comment]
Hi, naqvis, 我在 telegram 回复你啦，上次因为有事回复迟了，看你应该不常上电报吧， 方便的话，那边一起再交流下常用联系方式吧？
