### ISSUE TITLE
Fix for Crystal 0.31.0

### ISSUE THREAD

**Issue by j8r** [naqvis/crystar#2]
After bumping to Crystal 0.31.0, the library does not compile.
After modifying `/` to `//` in `SparseArray#max_entries` makes it compile again.
Then, when running specs, there are arithmetic overflows in the reader, and warnings about missing return types.

Another issues I have seen, there is a leaking file descriptor in `Read.open(filename : String`, because of `File.new`. I suggest to use `File.open` instead, then yielding the reader inside.

**Comment by girng** [comment]
Nice catch @j8r 👍
