### ISSUE TITLE
`Reader#each_entry` includes "pax_global_header"

### ISSUE THREAD

**Issue by j8r** [naqvis/crystar#5]
I don't think we want to have `pax_global_header` considered as a normal file?
I propose to ignore it.

**Comment by naqvis** [comment]
According to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html#tag_20_92_13_03) implementation is supposed to unpack an extended header as an ordinary file if it doesn't support them. Crystar only supports parsing and composing global headers, but does not currently support persisting the global state across files.
