### ISSUE TITLE
Version number mismatch

### ISSUE THREAD

**Issue by mwlang** [naqvis/crystar#9]
When installing shards for a Lucky Framework project, I encounter this warning:

> Shard "crystar" version (0.1.7) doesn't match tag version (0.1.8)

Looking at the master branch, I can see `0.1.7` is indeed still in the shard.yml as the version number.

**Comment by ZimbiX** [comment]
The version should probably move up to `0.1.9` - rather than fixing this by updating the version in the file then moving the tag.
